services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: adminTraider
      POSTGRES_PASSWORD: adminTraider
      POSTGRES_DB: trade_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: "b30f2f10-8839-4ebc-a8db-bfa76386bb42"
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - mynetwork

  order-matching-service:
    image: 642902937286.dkr.ecr.eu-north-1.amazonaws.com/order-matching-service:${IMAGE_TAG}
    container_name: order-matching-service
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trade_db
      SPRING_DATASOURCE_USERNAME: adminTraider
      SPRING_DATASOURCE_PASSWORD: adminTraider
    networks:
      - mynetwork
    depends_on:
      - kafka
      - postgres
    restart: always

  trade-execution-service:
    image: 642902937286.dkr.ecr.eu-north-1.amazonaws.com/trade-execution-service:latest
    container_name: trade-execution-service
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trade_db
      SPRING_DATASOURCE_USERNAME: adminTraider
      SPRING_DATASOURCE_PASSWORD: adminTraider
    networks:
      - mynetwork
    depends_on:
      - kafka
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_IMPORT: /opt/keycloak/data/trade-realm-export.json
    command:
      - start-dev
    ports:
      - "8082:8080"  # Expose on host port 8082
    volumes:
      - ./keycloak:/opt/keycloak/data
      - keycloak_data:/opt/keycloak/persistent_data
    networks:
      - mynetwork
    restart: unless-stopped

volumes:
  kafka_data:
  pgdata:
  keycloak_data:

networks:
  mynetwork:
    driver: bridge
    name: mynetwork
