services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: adminTraider
      POSTGRES_PASSWORD: adminTraider
      POSTGRES_DB: trade_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    environment:
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: "b30f2f10-8839-4ebc-a8db-bfa76386bb42"
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - mynetwork

  order-matching-service:
    image: 642902937286.dkr.ecr.eu-north-1.amazonaws.com/order-matching-service:latest
    container_name: order-matching-service
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trade_db
      SPRING_DATASOURCE_USERNAME: adminTraider
      SPRING_DATASOURCE_PASSWORD: adminTraider
    networks:
      - mynetwork
    depends_on:
      - kafka
      - postgres
    restart: always

  trade-execution-service:
    image: 642902937286.dkr.ecr.eu-north-1.amazonaws.com/trade-execution-service:latest
    container_name: trade-execution-service
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trade_db
      SPRING_DATASOURCE_USERNAME: adminTraider
      SPRING_DATASOURCE_PASSWORD: adminTraider
    networks:
      - mynetwork
    depends_on:
      - kafka
      - postgres

volumes:
  kafka_data:
  pgdata:

networks:
  mynetwork:
    driver: bridge
    name: mynetwork
